project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!slides/"
  resources: 
    - slides/
    - images/
    - coursework/

website:
  title: "Christy Choi"
  
  navbar:
    collapse: true
    collapse-below: lg
    background: light
    left: 
      - text: "Homepage"
        href: index.qmd
      - text: "Coursework"
        href: coursework.qmd
      - text: "CV"
        href: cv.qmd
      - icon: gear
        href: about.qmd
    right:
      - icon: github
        href: "https://github.com/christychoicc"

  sidebar:
    style: "docked"
    background: light
    search: false
    contents:
      - text: "---"

format:
  html:
    theme:
      light: [cosmo, flatly]
      dark: [cosmo, darkly]
    code-link: true
    toc: false
    css: styles.css
    include-before-body: _sidebar-profile.html

editor: visual