project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!slides/"
  resources:
    - slides/
    - images/
    - coursework/

execute:
  freeze: auto

website:
  title: "Christy Choi"
  page-navigation: true
  back-to-top-navigation: true
  open-graph: true

  navbar:
    background: white     # ← makes navbar white
    collapse: true
    collapse-below: lg
    right:
      - text: "Homepage"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Coursework"
        href: coursework.qmd
      - text: "CV"
        href: cv.qmd
      - icon: github
        href: "https://github.com/christychoicc"

  page-footer:
    left: >-
      &#169; 2026 Christy Choi
    right:
      Made with [Quarto](https://quarto.org)

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css:
      - styles.css
      - https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css
    toc: true
    code-link: true

editor: visual