project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!slides/"
  resources:
    - slides/
    - images/
    - coursework/

website:
  title: "Christy Choi"
  page-navigation: true
  back-to-top-navigation: true
  open-graph: true

  navbar:
    collapse: true
    collapse-below: lg
    right:
      - text: "Homepage"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Coursework"
        href: coursework.qmd
      - text: "CV"
        href: cv.qmd
      - icon: github
        href: "https://github.com/christychoicc"

format:
  html:
    theme:
      light: cosmo
      dark: brand
    css:
      - styles.css
    toc: true
    code-link: true

editor: visual