---
title: "About me..."
---

I am currently a Master's student at the Bartlett Centre for Advanced Spatial Analysis. I hold a Bachelor's degree in Planning and Real Estate from the University of Manchester. I am experienced in cleaning and analysing complex data sets, producing clear reporting, and translating evidence into practical recommendations. I am committed to applying digital analytics to navigate complexity and support well-informed, inclusive, long-term solutions through evidence-based decision-making.

View my [CV](cv.qmd) and [Coursework](coursework.qmd) →

## Technical Proficiency

**Languages**: Python, SQL, R, JavaScript

**Tools**: Git and GitHub, ArcGIS Pro, QGIS, SNAP, Google Earth Engine, NetLogo, Adobe Illustrator, Photoshop, Lightroom, Microsoft Word, Powerpoint, Excel

[View my GitHub →](https://github.com/christychoicc)

## Languages

-   Cantonese, English, Mandarin, German (Intermediate Level)

## Interests and Hobbies

-   Tennis, Running, Hiking, Pilates, Painting, Baking, Travelling
