---
title: "Coursework"
---

Welcome! This page showcases a collection of my academic coursework from my Master’s Degree in Urban Spatial Science and my Bachelor’s Degree in Planning and Real Estate. Both completed works and projects currently in progress are included in the below.

```{r, echo=FALSE}
xaringanExtra::embed_xaringan(
  url = "slides/coursework.html", 
  ratio = "16:9"
)
```

Note\* this set of slides is for presentation purpose only, View the full-screen version at: [Coursework Slides](https://christychoicc.github.io/slides/coursework.html)

## MSc Urban Spatial Science, University College London

### Spatial Analysis - CASA0005 Geographic Information Systems and Science

#### TfL Vision Zero

This is a spatial hotspot analysis examining where deaths and serious injuries cluster across London in 2024 using casualty data provided by TfL. The analysis applied point pattern analysis methods and spatial autocorrelation methods to identify statistically significant hotspot and coldspot areas and discuss policy implications for Vision Zero.

View the full report (HTML): [TfL Vision Zero](coursework/TfL-Vision-Zero.html){target="_blank"}

#### New York Evictions

This is a spatial hotspot analysis examining where eviction activities cluster across New York in 2020 using evictions data provided by NYC Open Data. The analysis applied point pattern analysis methods and spatial autocorrelation methods to identify statistically significant hotspot and coldspot areas, discussing areas to be prioritiesed for policy interventions.

View the full report (HTML): [New York Evictions](coursework/New-York-Evictions.html){target="_blank"}

#### Graffiti San Francisco

View the full report (HTML): coming soon…

### CASA0007 Quantitative Methods

#### House Prices and London Underground: Does Multiple Interchange Tube Stations Link with Higher London House Prices in 2024?

Do multi-line Tube interchanges relate to higher house prices in London? This report analysed 82k+ property sales in London in 2024 from HM Land Registry Price Paid Data to test whether the connectivity level of the nearest Underground station (single-line vs 2-line vs 3+ line interchange) is associated with sale prices, controlling for property types, distance to central London, distance to nearest Tube station, and deprivation indicies (IMD). The final model explained a substantial variance (R² ≈ 0.527) and found higher prices near multi-line interchanges. Some local neighbourhood effects remain visible in the unexplained part of the model, supported by a positive Moran’s I (≈0.389). A technical appendix is included within the report.

View the full report (PDF): \[London House Prices and Underground Regression Analysis 2024\] coming soon…

### CASA0023 Remotely Sensing Cities and Environments

View my Learning Diary (Webpage): [CASA0023 Remotely Sensing Cities and Environments 25/26 Learning Diary](https://christychoicc.github.io/RSCE/)

Note: This webpage is still in its building process, the full learning diary will be completed by April 2026.

## BSc Planning and Real Estate, University of Manchester

### Spatial Analysis, Transport - PLAN0010 Applied Project 22/23

This report analyses the transport infrastructure of Wilmslow, Cheshire, examining key themes including car ownership, public transport provision, and commuting patterns using data from the UK Census 2011 and Cheshire East Council. Spatial data analysis and choropleth mapping were produced using ArcGIS Pro, with supporting charts and data visualisations from Excel. A proposal report was also included, outlining actionable solutions of improved cycling infrastructure, car clubs, and travel card schemes to address the Wilmslow’s heavy car dependency and congestion issues.

View the full report (PDF): [Wilmslow Baseline Analysis and Proposal Report](coursework/wilmslow_appliedproject.pdf){target="_blank"}
