---
title: "Curriculum Vitae"
---

## Education

[Browse my coursework →](coursework.qmd)

### MSc, Urban Spatial Science, University College London (UCL), The Bartlett Faculty of the Built Environment, The Bartlett Centre for Advanced Spatial Analysis, U.K. \| 2025 - 2026

-   Royal Geographical Society (with IBG) Accredited

-   Modules include specialisation in Big Data, Urban Modelling and Simulation pathways:

    Urban Systems Theory; Geographic Information Systems and Science; Quantitative Methods; Foundations of Spatial Data Science; Data Science for Spatial Systems; Agent-based Modelling for Spatial Systems; Building Spatial Applications with Big Data; Remotely Sensing Cities and Environments; Dissertation.

### BSc Planning and Real Estate, University of Manchester, U.K. \| 2022 - 2025

-   RICS Accredited, RTPI Spatially Accredited

-   Final Grade: Second Class with Honours, Division One (2.1)

-   Dissertation: Explore The Role of Vertical Greenery Systems in Enhancing Urban Energy Efficiency in Dense Urban Areas, Strategies for Hong Kong.

-   Modules include: Developed a strong understanding in urban theories, policies and application of planning law principles to real world case studies. Gained practical experiences in valuation and appraisal analyses, plan-making, and applied development projects incorporating spatial analyses, developed data analytics skills to support evidence-based decision-making approaches in urban design and research.

-   Coursework Projects: Wilmslow Baseline Analysis and Proposal Report; Trafford Local Plan-Making - Transport, Development Management; Planning Application for Residential Development at Thornham Old Road, Oldham – Site Potential Evaluation and Design and Access Statement; Site Analysis and Local Character and Facilities with Map Making Illustrations; M3 1FB Context Analyses and Sustainable Development Final Project; M1 4HD Office Valuation Report, Housing Market Insights Report of Greater Manchester; Woodford Aerodrome, Stockport Public Local Planning Enquiry

Global Summer School \| 2022 \| TSINGHUA UNIVERSITY, CHINA

-   Subject Theme: A Healthy Planet for Sustainable Development

-   Modules include: Understanding challenges and propose solutions utilising AI in achieving digital inclusion for sign language users, implementing AI to promote inclusivity for all.

A-LEVELS & GCSES \| 2022 \| St, Mary's School, Calne, U.K.

-   A-Levels: Fine Art, Mathematics, Economics, Chinese (Traditional Chinese, Mandarin)

-   EPQ: Extended Project (Level 3) Qualifications 2022

-   Young Enterprise West England 2021- Best Innovation Award, Best Presentation Award, Best Report Award, Best Overall Award

-   GCSE: English Language, English Literature, Mathematics, Double Award in Science, Fine Art, Geography, German Language, Religious Studies

-   University of Oxford German Olympiad Award 2019 – Highly Commended

## Experience

### RTPI Student Member \| Royal Town Planning Institute (RTPI) \| September 2022 - 2025

### Operation Assistant Summer Internship \| Pacific Infrastructure Limited, Hong Kong \| July 2023 - August 2023

-   Assisted in the transition prior to the HKeToll system (smart mobility initiative for automated toll payments), monitoring CCTV footages for evasions, tracing vehicle owners and preparation of formal correspondence to ensure regulatory compliances.

### Retail Sales Specialist Part-Time \| Croyaki Tea Manchester, U.K. \| May 2023 – June 2023

-   Delivered high quality customer services in managing transactions, assisting beverage production.

### Landscape Architecture Summer Trainee \| SANFIELD (Management) LTD. Sun Hung Kai Properties, Hong Kong\| July 2021 – August 2021

-   Assisted in material selection, planning and execution of landscape projects, on site showroom preparation for Central Peak property development.

-   Conducted a design project for a public park redevelopment (internship department assessment), translation of design concepts into practical solutions, using Auto CAD, Sketchup and Photoshop.

### Design Assistant Internship \| GYSO PEARLS & JEWELLERY LTD, Hong Kong \| July 2020 – August 2020

-   Managed showroom materials, photoshop edits for marketing visuals. Skills & Achievements

## Skills

### Technical

-   Microsoft Word, PowerPoint, Excel; Adobe Photoshop, Lightroom, Illustrator

-   Python; SQL; R and R Studio

-   QGIS; ArcGIS Pro; NetLOGO; SNAP; Google Earth Engine

-   Git; GitHub

-   Basic Knowledge in AutoCAD and SketchUp

### Languages

-   English; Cantonese; Mandarin; German (Intermediate Level)

### Qualifications

-   RADA (Royal Academy of Dramatic Arts) Advanced Communication Course – Certificate of Completion 2021

-   BCS Level 2 ECDL – IT User Skills 2020

-   Duke of Edinburgh Scheme – Bronze Award 2019

### Volunteer

-   Volunteering in assisting food distributions in local communities, privately organised with family and personal networks to support underserved individuals in our community.

-   Agency for Volunteer Service Hong Kong – Volunteer Member

-   Crossroads Foundation – Crossroad’s Global Distribution – Computer Department, AVS Miracle Summer Programme August 2024

### Interests and Hobbies

-   Tennis, Running, Hiking, Pilates, Painting, Baking, Travelling

[Learn more about me →](about.qmd)
